[user]
name = "Alex Plescan"
email = "alexpls@fastmail.com"

[ui]
default-command = "log"
editor = "nvim"

[signing]
sign-all = true
backend = "gpg"
key = "0C88A905360A073F"

[git]
push-bookmark-prefix = "alexpls/push-"

[aliases]
l = ["log", "-r", "ancestors(@)"]
fresh = ["util", "exec", "--", "bash", "-c", """
#!/usr/bin/env bash

set -e

jj git fetch
jj new 'trunk()'
""", ""]

