set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Wrap git commit messages after 72 characters.
" See https://stackoverflow.com/a/11023282/1432982
filetype plugin on
au FileType gitcommit setlocal tw=72

" Ignore case when searching
set ignorecase